name: deploy to lambda
on:
  push:
    branches: ['master']
jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies for Test
        run: |
          pip3 install -r requirements_dev.txt
      - name: Run Tests
        run: |
          pytest
      - name: Install Dependencies for deployment
        run: |
          pip3 install --target ./src -r requirements.txt
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./src/*
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          function_name: freshtoons_update
          zip_file: bundle.zip
